[package]
name = "projet"
version = "0.1.0"
authors = ["matthieurobert <matthieurobert82@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.21"
rand = "0.6.5"